# Generated by Django 4.0.6 on 2022-07-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel congue enim. Fusce nec nibh blandit, finibus tellus sit amet, eleifend neque. Nunc vehicula velit malesuada, dapibus arcu eu, convallis tellus.'),
        ),
    ]
