# Generated by Django 4.0.6 on 2022-08-30 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_note_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
